import { useEffect, useState } from "react";

import { Spin } from "antd";

import { TenantContext, Tenant } from "../context/TenantContext";

const applyFavicon = (faviconUrl?: string) => {
  if (!faviconUrl) return;
  let link = document.querySelector<HTMLLinkElement>("link[rel~='icon']");
  if (!link) {
    link = document.createElement("link");
    link.rel = "icon";
    document.head.appendChild(link);
  }
  link.href = faviconUrl;
};

export default function TenantProvider({ children }: { children: React.ReactNode }) {
  const [tenant, setTenant] = useState<Tenant | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    // tenant.json is generated by scripts/fetch-tenant.js (runs as prestart/prebuild),
    // so this is a same-origin fetch with no CORS concerns.
    fetch("/tenant.json", { cache: "no-store" })
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data: Tenant) => {
        if (cancelled) return;
        setTenant(data);
        applyFavicon(data?.assets?.faviconUrl);
        if (data?.brand?.name) {
          const suffix = data.brand.productSuffix ? ` ${data.brand.productSuffix}` : "";
          document.title = `${data.brand.name}${suffix}`;
        }
      })
      .catch((err) => {
        if (cancelled) return;
        setError(err?.message || "Failed to load tenant config");
      });

    return () => {
      cancelled = true;
    };
  }, []);

  if (error) {
    return (
      <div className="h-screen w-screen flex flex-col items-center justify-center gap-2 text-center p-6">
        <div className="text-lg font-semibold">Tenant configuration could not be loaded</div>
        <div className="text-sm text-gray-500">{error}</div>
      </div>
    );
  }

  if (!tenant) {
    return (
      <div className="h-screen w-screen flex items-center justify-center">
        <Spin />
      </div>
    );
  }

  return <TenantContext.Provider value={tenant}>{children}</TenantContext.Provider>;
}
